### ISSUE TITLE
https://csvj.org/ and https://metacpan.org/pod/CSVJF disagree about newlines

### ISSUE THREAD

**Issue by jwrightecs** [perlancar/perl-CSVJF#1]
CSVJF.pod seems to allow for embedded newlines in JSON-encoded strings, but csvj.org encodes newlines as \n inside "s

**Comment by perlancar** [comment]
Sorry for the late response. I didn't see the notification.

I've added a note to make it clearer that CSVJ and CSVJF are unrelated.
